### ISSUE TITLE
This project seems incompatible with black

### ISSUE THREAD

**Issue by bristea** [zheller/flake8-quotes#105]
It seems that this project seems to be totally opposed to black double quoting and that is causing havoc if someone happens to install this plugin at user level flake8, as it will make flake8 report false errors in other projects.

**Comment by twolfson** [comment]
This project can be configured with single or double quotes. It's also unexpected that someone would use both `black` and `flake8-quotes` in the same project as they both revolve around styling

Using user-wide or system-wide linting rules is not recommended due to the diversity of choices made by various projects.
