### ISSUE TITLE
This plugin should not work except explicit configed

### ISSUE THREAD

**Issue by virusdefender** [zheller/flake8-quotes#51]
I only want to check quotes in some specific projects, however, once this plugin is installed, it will work in all flake8 check task

![image](https://cloud.githubusercontent.com/assets/4939404/22632667/6b79d600-ec56-11e6-8580-2d0aee1c654e.png)

**Comment by twolfson** [comment]
`flake8` is built to automatically enable/detect plugins. All other plugins are similarly configured to lint with default conditons. The typical convention to prevent this scenario is to set up a virtual environment for each specific project instead of assuming all projects will be configured/linted consistently.

Here are useful tools for virtual environments:

- https://virtualenv.pypa.io/en/stable/
- https://virtualenvwrapper.readthedocs.io/en/latest/
